// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYruhMSR56nSA1Li4nhgDgxfuqE3QJiDM',
    appId: '1:447748979936:web:4d64bb2095e7497b28e485',
    messagingSenderId: '447748979936',
    projectId: 'authtutorial-a4202',
    authDomain: 'authtutorial-a4202.firebaseapp.com',
    storageBucket: 'authtutorial-a4202.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwNbvOVHNGYdjMiXe9NKUPkwYXwy8Evdg',
    appId: '1:447748979936:android:cde362039a35d9e428e485',
    messagingSenderId: '447748979936',
    projectId: 'authtutorial-a4202',
    storageBucket: 'authtutorial-a4202.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJhS2LVxae4-1AcPt6UTgEmFq7Rypf0Kg',
    appId: '1:447748979936:ios:b3269ccf4c18b46128e485',
    messagingSenderId: '447748979936',
    projectId: 'authtutorial-a4202',
    storageBucket: 'authtutorial-a4202.appspot.com',
    iosBundleId: 'com.example.tasklocal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJhS2LVxae4-1AcPt6UTgEmFq7Rypf0Kg',
    appId: '1:447748979936:ios:f46bbb118c0b262928e485',
    messagingSenderId: '447748979936',
    projectId: 'authtutorial-a4202',
    storageBucket: 'authtutorial-a4202.appspot.com',
    iosBundleId: 'com.example.tasklocal.RunnerTests',
  );
}
